#!/bin/sh

cd ${0%/*} || exit 1 

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication surfaceFeatures 	

runApplication blockMesh	

runApplication decomposePar -copyZero
runParallel snappyHexMesh -overwrite

runParallel patchSummary
runApplication reconstructParMesh -constant
runParallel potentialFoam
runParallel $(getApplication)

sleep 10
foamMonitor -l postProcessing/residuals/0/residuals.dat

runApplication reconstructParMesh -constant
runApplication reconstructPar
simpleFoam -postProcess -func wallShearStress
#postProcess -dict sampleDict -latestTime

runApplication paraFoam

#------------------------------------------------------------------------------
